title: Navid Asadi
name: Navid's personal website
# url: http://localhost:4000
# url: https://nrasadi.github.io

dir_addrs:
  statics: /statics/
  photos: /statics/photos/
  fonts: /statics/fonts/
  icons: /statics/icons/
  styles: /styles/
  scripts: /scripts/

collections:
  courses:
    output: true
  resources:
    output: true
  publications:
    output: false

highlighter: rouge
future: false

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
 math_engine: mathjax
