title: Navid Asadi
name: Navid's personal website
# url: http://localhost:4000
# url: https://nrasadi.github.io

constants:
  max_related_posts: 5
  max_latest_posts: 1
  load_new_posts: 2

permalink: /:categories/:title:output_ext

dir_addrs:
  statics: /statics/
  photos: /statics/photos/
  fonts: /statics/fonts/
  icons: /statics/icons/
  styles: /styles/
  scripts: /scripts/

collections:
  courses:
    output: true
  resources:
    output: true
  publications:
    output: false
  ml_systems:
    output: true

defaults:
  - scope:
      path: ""
      type: "ml_systems"
    values:
      layout: "ml_systems_post"
  - scope:
      path: ""
    values:
      layout: "default"

highlighter: rouge
future: false

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
 math_engine: mathjax
